// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from msgid.proto</summary>
  public static partial class MsgidReflection {

    #region Descriptor
    /// <summary>File descriptor for msgid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgidReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgttc2dpZC5wcm90bxIIcHJvdG9jb2wqFwoFTVNHSUQSDgoKTVNHSURfQkFT",
            "RRAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MSGID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MSGID {
    [pbr::OriginalName("MSGID_BASE")] Base = 0,
  }

  #endregion

}

#endregion Designer generated code
