------------------------
--怪物卡牌测试员
------------------------
return {
    baseid = 1002,
    name = {cn="怪物卡牌测试员",en=""},
    desc = {cn="一个只有10点血的家伙",en=""},
    resource = {quality=1,icon="Sprites/EntityHead/DEFAULT",uiModel="Models/UI/UI_wu",mapModel="Models/Map/Map_wu",matchModel="Models/Battle/Bat_wu"},
    career = 2,
    category = 2,
    level = 0,
    levelup_baseid = 0,
    inithp = 150,
    maxhp = 150,
    round_mp = 1,
    strength = 0,
    armor = 0,
    shield = 0,
    init_gold = 999,
    init_cards = {10010,10010,10010,10010,10010},
    max_cards = 100,
    init_buffs = {},
    init_items = {},
    init_puppets = {},
    round_cards = 1,
    max_hold_cards = 0,
    max_puppets = 0,
    max_pack_slots = 99,
    max_equip_slots = 0,
    purchase_card_script_func = nil,
    destroy_card_script_func = nil,
}
