------------------------
--盗贼
------------------------
return {
    baseid = 101,
    name = {cn="【午】",en=""},
    desc = {cn="午，使用枪械攻击敌人，目前无成型流派",en=""},
    resource = null,
    career = 1,
    category = 1,
    level = 1,
    levelup_baseid = 0,
    inithp = 99,
    maxhp = 99,
    round_mp = 2,
    strength = 0,
    armor = 0,
    shield = 0,
    init_gold = 999,
    init_cards = {10480,10480,10480,10480,10480,10490,10500,},
    max_cards = 100,
    init_buffs = {},
    init_items = {},
    init_puppets = {},
    round_cards = 3,
    max_hold_cards = 0,
    max_puppets = 10,
    max_pack_slots = 99,
    max_equip_slots = 10,
    purchase_card_script_func = nil,
    destroy_card_script_func = nil,
}
