------------------------
--卡牌测试员
------------------------
return {
    baseid = 1305,
    name = {cn="宠物5",en=""},
    desc = {cn="数据库的卡他都有",en=""},
    resource = {quality=1,icon="Sprites/EntityHead/pet_zhanqi",uiModel="Models/UI/UI_zhanqi",mapModel="Models/Map/Map_wu",matchModel="Models/Battle/Bat_zhanqi"},
    career = 1,
    category = 2,
    level = 1,
    levelup_baseid = 0,
    inithp = 99,
    maxhp = 99,
    round_mp = 1,
    strength = 0,
    armor = 0,
    shield = 0,
    init_gold = 999,
    init_cards = {10010},
    max_cards = 100,
    init_buffs = {},
    init_items = {},
    init_puppets = {},
    round_cards = 3,
    max_hold_cards = 0,
    max_puppets = 0,
    max_pack_slots = 99,
    max_equip_slots = 0,
    purchase_card_script_func = nil,
    destroy_card_script_func = nil,
}
