// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_INCLUDED_common_2eproto
#define PROTOBUF_INCLUDED_common_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_common_2eproto 

namespace protobuf_common_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_common_2eproto
namespace protocol {
class Coord;
class CoordDefaultTypeInternal;
extern CoordDefaultTypeInternal _Coord_default_instance_;
}  // namespace protocol
namespace google {
namespace protobuf {
template<> ::protocol::Coord* Arena::CreateMaybeMessage<::protocol::Coord>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protocol {

enum GENDER {
  MALE = 0,
  FEMALE = 1,
  GENDER_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GENDER_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GENDER_IsValid(int value);
const GENDER GENDER_MIN = MALE;
const GENDER GENDER_MAX = FEMALE;
const int GENDER_ARRAYSIZE = GENDER_MAX + 1;

const ::google::protobuf::EnumDescriptor* GENDER_descriptor();
inline const ::std::string& GENDER_Name(GENDER value) {
  return ::google::protobuf::internal::NameOfEnum(
    GENDER_descriptor(), value);
}
inline bool GENDER_Parse(
    const ::std::string& name, GENDER* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GENDER>(
    GENDER_descriptor(), name, value);
}
// ===================================================================

class Coord : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.Coord) */ {
 public:
  Coord();
  virtual ~Coord();

  Coord(const Coord& from);

  inline Coord& operator=(const Coord& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Coord(Coord&& from) noexcept
    : Coord() {
    *this = ::std::move(from);
  }

  inline Coord& operator=(Coord&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Coord& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Coord* internal_default_instance() {
    return reinterpret_cast<const Coord*>(
               &_Coord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Coord* other);
  friend void swap(Coord& a, Coord& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Coord* New() const final {
    return CreateMaybeMessage<Coord>(NULL);
  }

  Coord* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Coord>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Coord& from);
  void MergeFrom(const Coord& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Coord* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:protocol.Coord)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_common_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Coord

// float x = 1;
inline void Coord::clear_x() {
  x_ = 0;
}
inline float Coord::x() const {
  // @@protoc_insertion_point(field_get:protocol.Coord.x)
  return x_;
}
inline void Coord::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:protocol.Coord.x)
}

// float y = 2;
inline void Coord::clear_y() {
  y_ = 0;
}
inline float Coord::y() const {
  // @@protoc_insertion_point(field_get:protocol.Coord.y)
  return y_;
}
inline void Coord::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:protocol.Coord.y)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::protocol::GENDER> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::GENDER>() {
  return ::protocol::GENDER_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_common_2eproto
