------------------------
--备注
------------------------
return {
    baseid = 10030,
    name = {cn="【#3虚弱打击】",en=""},
    desc = {cn="对目标造成5伤害并使其获得【弱】x2.",en=""},
    icon = "Sprites/CardFace/com19",
    play_animate = "Attack",
    play_effect = "null",
    effect_type = 0,
    effect_slot = "0",
    quality = 0,
    category = 2,
    level = 1,
    levelup_baseid = 10031,
    require_career = 0,
    require_gender = 0,
    enable_play = true,
    enable_equip = false,
    enable_discard = true,
    cost_mp = 0,
    resume_mp = 0,
    settle_play = true,
    settle_discard = false,
    settle_equip = false,
    settle_times = 1,
    require_target = 2,
    damage_type = 1,
    damage_value = 5,
    effect_hp = 0,
    effect_mp = 0,
    effect_strength = 0,
    effect_armor = 0,
    effect_shield = 0,
    effect_buff = {[3005]=2,},
    draw_stacknewone = {},
    draw_stackdeal = 0,
    draw_stackdiscard = 0,
    draw_stackexhaust = 0,
    shuffle_stackdiscard = false,
    shuffle_stackexhaust = false,
    into_stackdiscard = true,
    into_stackexhaust = false,
    into_destroy = false,
    price_gold = 100,
    price_diamond = 100,
    script_func = CardScript.common,
}
