------------------------
--备注
------------------------
return {
    baseid = 10140,
    name = {cn="连击",en=""},
    desc = {cn="使你下1次的攻击牌生效2次",en=""},
    icon = "Sprites/CardFace/com01",
    play_animate = "Cast",
    play_effect = "null",
    effect_type = 0,
    effect_slot = "0",
    quality = 0,
    category = 3,
    level = 1,
    levelup_baseid = 0,
    require_career = 0,
    require_gender = 0,
    enable_play = true,
    enable_equip = false,
    enable_discard = true,
    cost_mp = 1,
    resume_mp = 0,
    settle_play = true,
    settle_discard = false,
    settle_equip = false,
    settle_times = 0,
    require_target = 3,
    damage_type = 0,
    damage_value = 0,
    effect_hp = 0,
    effect_mp = 0,
    effect_strength = 0,
    effect_armor = 0,
    effect_shield = 0,
    effect_buff = {},
    draw_stacknewone = {},
    draw_stackdeal = 0,
    draw_stackdiscard = 0,
    draw_stackexhaust = 0,
    shuffle_stackdiscard = false,
    shuffle_stackexhaust = false,
    into_stackdiscard = false,
    into_stackexhaust = false,
    into_destroy = true,
    price_gold = 100,
    price_diamond = 100,
    script_func = CardScript.common,
}
