------------------------
--备注
------------------------
return {
    baseid = 10151,
    name = {cn="【#15普通攻击*+】",en=""},
    desc = {cn="造成8点物理伤害",en=""},
    icon = "null",
    play_animate = "Attack",
    play_effect = "null",
    effect_type = 0,
    effect_slot = "0",
    quality = 0,
    category = 1,
    level = 2,
    levelup_baseid = 0,
    require_career = 0,
    require_gender = 0,
    enable_play = true,
    enable_equip = false,
    enable_discard = true,
    cost_mp = 0,
    resume_mp = 0,
    settle_play = true,
    settle_discard = false,
    settle_equip = false,
    settle_times = 1,
    require_target = 2,
    damage_type = 1,
    damage_value = 8,
    effect_hp = 0,
    effect_mp = 0,
    effect_strength = 0,
    effect_armor = 0,
    effect_shield = 0,
    effect_buff = {},
    draw_stacknewone = {},
    draw_stackdeal = 0,
    draw_stackdiscard = 0,
    draw_stackexhaust = 0,
    shuffle_stackdiscard = false,
    shuffle_stackexhaust = false,
    into_stackdiscard = false,
    into_stackexhaust = true,
    into_destroy = false,
    price_gold = 100,
    price_diamond = 100,
    script_func = CardScript.common,
}
