------------------------
--备注
------------------------
return {
    baseid = 10340,
    name = {cn="急行",en=""},
    desc = {cn="造成1点【物理伤害】,【抽牌】1张,恢复1点【能量】",en=""},
    icon = "null",
    play_animate = "Attack",
    play_effect = "null",
    effect_type = 0,
    effect_slot = "0",
    quality = 0,
    category = 0,
    level = 1,
    levelup_baseid = 10341,
    require_career = 0,
    require_gender = 0,
    enable_play = true,
    enable_equip = false,
    enable_discard = true,
    cost_mp = 1,
    resume_mp = 1,
    settle_play = true,
    settle_discard = false,
    settle_equip = false,
    settle_times = 1,
    require_target = 0,
    damage_type = 1,
    damage_value = 1,
    effect_hp = 0,
    effect_mp = 0,
    effect_strength = 0,
    effect_armor = 0,
    effect_shield = 0,
    effect_buff = {},
    draw_stacknewone = {},
    draw_stackdeal = 1,
    draw_stackdiscard = 0,
    draw_stackexhaust = 0,
    shuffle_stackdiscard = false,
    shuffle_stackexhaust = false,
    into_stackdiscard = true,
    into_stackexhaust = false,
    into_destroy = false,
    price_gold = 100,
    price_diamond = 5,
    script_func = CardScript.common,
}
